name: Build and deploy JAR app to Azure Web App  -  park-share

on:
  push:
    branches:
      - main
    paths:
      - /src/main/resources/rsa.private
      - /src/main/resources/rsa.public
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      # Novo passo para dar permissão de execução ao script
      - name: Give execute permission to generate_keys.sh
        run: chmod +x ./generate_keys.sh

      # Passo para rodar o script
      - name: Run generate_keys.sh
        run: ./generate_keys.sh
      
      - name: List files to verify RSA keys
        run: ls -la

      - name: Upload RSA public key
        uses: actions/upload-artifact@v3
        with:
          name: rsa-public
          path: src/main/resources/rsa.public

      - name: Upload RSA private key
        uses: actions/upload-artifact@v3
        with:
          name: rsa-private
          path: src/main/resources/rsa.private

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Download RSA public key
        uses: actions/download-artifact@v3
        with:
          name: rsa-public

      - name: Download RSA private key
        uses: actions/download-artifact@v3
        with:
          name: rsa-private
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'park-share'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_86DE118439A543F2996E6592F3D222C3 }}
      
      - name: List files to verify RSA keys
        run: ls -la
